-- Converted view (MariaDB-compatible)

CREATE OR REPLACE VIEW uihelper_stock_entries AS
SELECT
	s.id AS id,
	s.product_id,
	s.amount,
	s.best_before_date,
	s.purchased_date,
	s.stock_id,
	s.price,
	s.open,
	s.opened_date,
	s.row_created_timestamp,
	s.location_id,
	s.shopping_location_id,
	s.note,
	p.id AS product_id_view,
	p.name,
	p.description,
	p.product_group_id,
	p.active,
	p.location_id AS product_location_id,
	p.shopping_location_id AS product_shopping_location_id,
	p.qu_id_purchase,
	p.qu_id_stock,
	p.min_stock_amount,
	p.default_best_before_days,
	p.default_best_before_days_after_open,
	p.default_best_before_days_after_freezing,
	p.default_best_before_days_after_thawing,
	p.picture_file_name,
	p.enable_tare_weight_handling,
	p.tare_weight,
	p.not_check_stock_fulfillment_for_recipes,
	p.parent_product_id,
	p.calories,
	p.cumulate_min_stock_amount_of_sub_products,
	p.due_type,
	p.quick_consume_amount,
	p.hide_on_stock_overview,
	p.default_stock_label_type,
	p.should_not_be_frozen,
	p.treat_opened_as_out_of_stock,
	p.no_own_stock,
	p.default_consume_location_id,
	p.move_on_open,
	p.row_created_timestamp AS product_row_created_timestamp,
	p.qu_id_consume,
	p.auto_reprint_stock_label,
	p.quick_open_amount,
	p.qu_id_price,
	p.disable_open,
	p.default_purchase_price_type,
	p.has_sub_products,
	p.qu_factor_purchase_to_stock,
	p.qu_factor_consume_to_stock,
	p.qu_factor_price_to_stock
FROM stock s
JOIN products_view p
	ON s.product_id = p.id
/* uihelper_stock_entries(id,product_id,amount,best_before_date,purchased_date,stock_id,price,open,opened_date,row_created_timestamp,location_id,shopping_location_id,note,"id:1",name,description,product_group_id,active,"location_id:1","shopping_location_id:1",qu_id_purchase,qu_id_stock,min_stock_amount,default_best_before_days,default_best_before_days_after_open,default_best_before_days_after_freezing,default_best_before_days_after_thawing,picture_file_name,enable_tare_weight_handling,tare_weight,not_check_stock_fulfillment_for_recipes,parent_product_id,calories,cumulate_min_stock_amount_of_sub_products,due_type,quick_consume_amount,hide_on_stock_overview,default_stock_label_type,should_not_be_frozen,treat_opened_as_out_of_stock,no_own_stock,default_consume_location_id,move_on_open,"row_created_timestamp:1",qu_id_consume,auto_reprint_stock_label,quick_open_amount,qu_id_price,disable_open,default_purchase_price_type,has_sub_products,qu_factor_purchase_to_stock,qu_factor_consume_to_stock,qu_factor_price_to_stock) */;;
