CREATE TABLE products (
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT UNIQUE,
	name VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL UNIQUE,
	description TEXT,
	product_group_id INTEGER,
	active TINYINT NOT NULL DEFAULT 1 /* REVIEW: CHECK */ /* CHECK converted: CHECK(active IN (0, 1)) */,
	location_id INTEGER NOT NULL,
	shopping_location_id INTEGER,
	qu_id_purchase INTEGER NOT NULL,
	qu_id_stock INTEGER NOT NULL,
	min_stock_amount INTEGER NOT NULL DEFAULT 0,
	default_best_before_days INTEGER NOT NULL DEFAULT 0,
	default_best_before_days_after_open INTEGER NOT NULL DEFAULT 0,
	default_best_before_days_after_freezing INTEGER NOT NULL DEFAULT 0,
	default_best_before_days_after_thawing INTEGER NOT NULL DEFAULT 0,
	picture_file_name TEXT,
	enable_tare_weight_handling TINYINT NOT NULL DEFAULT 0,
	tare_weight REAL NOT NULL DEFAULT 0,
	not_check_stock_fulfillment_for_recipes TINYINT DEFAULT 0,
	parent_product_id INT,
	calories INTEGER,
	cumulate_min_stock_amount_of_sub_products TINYINT DEFAULT 0,
	due_type TINYINT NOT NULL DEFAULT 1 /* REVIEW: CHECK */ /* CHECK converted to ENUM: CHECK(due_type IN (1, 2)) */,
	quick_consume_amount REAL NOT NULL DEFAULT 1,
	hide_on_stock_overview TINYINT NOT NULL DEFAULT 0 /* REVIEW: CHECK */ /* CHECK converted: CHECK(hide_on_stock_overview IN (0, 1)) */,
	default_stock_label_type INTEGER NOT NULL DEFAULT 0,
	should_not_be_frozen TINYINT NOT NULL DEFAULT 0 /* REVIEW: CHECK */ /* CHECK converted: CHECK(should_not_be_frozen IN (0, 1)) */,
	treat_opened_as_out_of_stock TINYINT NOT NULL DEFAULT 1 /* REVIEW: CHECK */ /* CHECK converted: CHECK(treat_opened_as_out_of_stock IN (0, 1)) */,
	no_own_stock TINYINT NOT NULL DEFAULT 0 /* REVIEW: CHECK */ /* CHECK converted: CHECK(no_own_stock IN (0, 1)) */,
	default_consume_location_id INTEGER,
	move_on_open TINYINT NOT NULL DEFAULT 0 /* REVIEW: CHECK */ /* CHECK converted: CHECK(move_on_open IN (0, 1)) */,
	row_created_timestamp DATETIME DEFAULT CURRENT_TIMESTAMP /* REVIEW: was datetime('now','localtime') */
, qu_id_consume INTEGER, auto_reprint_stock_label TINYINT NOT NULL DEFAULT 0 /* REVIEW: CHECK */ /* CHECK converted: CHECK(auto_reprint_stock_label IN (0, 1)) */, quick_open_amount REAL NOT NULL DEFAULT 1, qu_id_price INTEGER, disable_open TINYINT NOT NULL DEFAULT 0 /* REVIEW: CHECK */ /* CHECK converted: CHECK(disable_open IN (0, 1)) */, default_purchase_price_type TINYINT NOT NULL DEFAULT 1 /* REVIEW: CHECK */ /* CHECK converted to ENUM: CHECK(default_purchase_price_type IN (1, 2, 3)) */, parent_or_self_id INTEGER) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
